// Generated by CoffeeScript 1.3.3
var collections,
  __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

collections = {
  id: null,
  userId: null,
  name: "我的愿望清单",
  placesData: [],
  itemsData: {},
  init: function() {
    var o, userId;
    o = this;
    userId = $.cookie("uid");
    userId = (userId ? userId : null);
    this.userId = userId;
    $("dl.sidebar a.clear").click(function() {
      if (!o.userId) {
        return alert("请先登陆");
      }
      return dialog("移除清单", "#dialog-del", "300");
    });
    $(".box .add").click(function() {
      if (!o.userId) {
        return alert("请先登陆");
      }
      return o.addPlace($(this).data());
    });
    $(".w750").delegate("button.remove", "click", function(event) {
      event.preventDefault();
      if (!o.userId) {
        return alert("请先登陆");
      }
      return o.addPlace($(this).data());
    });
    $("dl.sidebar").delegate("a.delete", "click", function() {
      if (!o.userId) {
        return alert("请先登陆");
      }
      return o.removePlace($(this).data("aid"));
    });
    return $("dl.sidebar dd.last .plan").click(function() {
      if (!o.userId) {
        return alert("请先登陆");
      }
      return window.location = "/plan/" + o.id + "/edit";
    });
  },
  newCollection: function() {
    this.resetView();
    this.id = null;
    this.name = $("#diglogBox #diglogInner #new_collection_name").val();
    this.placesData = [];
    return this.renderView();
  },
  addPlace: function(itemData) {
    var me, place, userId, _i, _len, _ref;
    if (!itemData.id) {
      return;
    }
    itemData.id += "";
    itemData.city_id += '';
    userId = $.cookie("uid");
    if (!userId) {
      return alert("请先登陆");
    }
    me = this;
    _ref = me.placesData;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      place = _ref[_i];
      if (place.id === itemData.id) {
        return alert("该地点已经在你的清单中");
      }
    }
    return $.ajax({
      contentType: 'application/json',
      data: $.toJSON({
        container: -1,
        place_type: itemData.type,
        place_id: itemData.id
      }),
      dataType: 'json',
      type: 'POST',
      processData: false,
      url: "/api/plans/" + me.id + "/activities/",
      success: (function(ac) {
        if (!ac.id) {
          return;
        }
        ac.place.aid = ac.id;
        me.placesData.push(ac.place);
        return me.renderView();
      })
    });
  },
  removePlace: function(aid) {
    var aids, aidstr, o, place, places, _i, _len, _ref, _ref1;
    aids = $.isArray(aid) ? aid : [aid + ""];
    aidstr = aids.join(',');
    o = this;
    places = [];
    _ref = this.placesData;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      place = _ref[_i];
      if (_ref1 = place.aid, __indexOf.call(aids, _ref1) >= 0) {
        continue;
      }
      places.push(place);
    }
    return $.ajax({
      type: 'DELETE',
      url: "/api/plans/" + o.id + "/activities/" + aidstr + "?force=1",
      success: function() {
        o.placesData = places;
        return o.renderView();
      }
    });
  },
  clearCurCity: function() {
    var aids, place, _i, _len, _ref;
    aids = [];
    _ref = this.placesData;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      place = _ref[_i];
      if (place.city_id === _CITY_ID) {
        aids.push(place.aid);
      }
    }
    return this.removePlace(aids);
  },
  renderView: function() {
    var $c, html, i, tabHtml, viewData, _results;
    this.resetView();
    viewData = {
      id: this.id,
      name: this.name,
      cities: {}
    };
    $c = $("dl.sidebar");
    $(".collection_name", $c).text(viewData.name);
    if (this.placesData.length < 1) {
      return;
    }
    for (i in this.placesData) {
      if (!viewData.cities[this.placesData[i].city_id]) {
        viewData.cities[this.placesData[i].city_id] = {
          id: this.placesData[i].city_id,
          name: this.placesData[i].city_name,
          places: []
        };
      }
      viewData.cities[this.placesData[i].city_id].places.push(this.placesData[i]);
    }
    tabHtml = "";
    for (i in viewData.cities) {
      if (i === _CITY_ID) {
        tabHtml += " " + viewData.cities[i].name;
      } else {
        tabHtml += "<a href=\"/attraction/" + i + "\">" + viewData.cities[i].name + "</a>";
      }
      tabHtml += "<span>(" + viewData.cities[i].places.length + ")</span>";
    }
    $(".tab", $c).html(tabHtml);
    if (!viewData.cities[_CITY_ID]) {
      return;
    }
    _results = [];
    for (i in viewData.cities[_CITY_ID].places) {
      html = "<p class=\"cl_item\">";
      html += "<img src=\"" + viewData.cities[_CITY_ID].places[i].cover + "\" width=\"230\" height=\"90\" alt=\"" + viewData.cities[_CITY_ID].places[i].name + "\">";
      html += "<strong class=\"bg\"></strong>";
      html += "<strong><span><a href=\"/" + viewData.cities[_CITY_ID].places[i].type + "/" + _CITY_ID + "/detail/" + viewData.cities[_CITY_ID].places[i].id + "\" target=\"_blank\">进入详情</a> <a class=\"delete\" data-aid=\"" + viewData.cities[_CITY_ID].places[i].aid + "\" href=\"javascript:void(0)\">移除</a></span>" + viewData.cities[_CITY_ID].places[i].name + "</strong>";
      html += "</p>";
      switch (viewData.cities[_CITY_ID].places[i].type) {
        case "attraction":
          _results.push($("dl.list dd.sight .tip", $c).before(html));
          break;
        case "restaurant":
          _results.push($("dl.list dd.restaurant .tip", $c).before(html));
          break;
        case "hotel":
          _results.push($("dl.list dd.hotel .tip", $c).before(html));
          break;
        default:
          _results.push(void 0);
      }
    }
    return _results;
  },
  resetView: function() {
    var $c;
    $c = $("dl.sidebar");
    $(".collection_name", $c).text("我的愿望清单");
    $(".tab", $c).html("");
    return $("dl.list .cl_item", $c).remove();
  },
  fetch: function(id) {
    var o;
    if (!this.userId) {
      return;
    }
    o = this;
    return $.get("/api/collections/", {
      user_id: this.userId
    }, (function(data) {
      if (!data.id) {
        return;
      }
      o.id = data.id;
      o.name = data.name;
      o.placesData = data.places;
      return o.renderView();
    }), "json");
  }
};

$(function() {
  return collections.init();
});
