// Generated by CoffeeScript 1.3.3
var new_load_attr;

new_load_attr = function(position, page, callback) {
  var from_city, me, to_city, to_price, url;
  if (page == null) {
    page = 1;
  }
  me = this;
  from_city = $('div.choose-city input').val();
  to_city = $.cookie('to_city');
  to_city || (to_city = '');
  to_price = parseInt($('.price').text().replace('元', ''));
  set_cookie('to_price', to_price);
  set_cookie('from_city', from_city);
  url = "/pagehome/attractions_by_price?from_city=" + (encodeURIComponent(from_city)) + "&to_city=" + (encodeURIComponent(to_city)) + "&from_price=0&to_price=" + to_price;
  if (position === 'filter') {
    set_cookie('to_price', null);
    if (callback) {
      $('ul.filter').load("" + url + "&view_type=lib_filter", callback);
    } else {
      $('ul.filter').load("" + url + "&view_type=lib_filter");
    }
  } else if (position === 'result') {
    if (callback) {
      $('li.result').load("" + url + "&view_type=lib_result", callback);
    } else {
      $('li.result').load("" + url + "&view_type=lib_result");
    }
  } else if (position === 'main') {
    if (callback) {
      $('div.main').load("" + url + "&page=" + page, callback);
    } else {
      $('div.main').load("" + url + "&page=" + page);
    }
  }
  return console.log(url);
};

$(function() {
  $('.chooseCity_popup a').click(function() {
    var $cwrapper, $input, callback, city, from_city;
    from_city = $(this).text();
    $cwrapper = $(this).parents('.choose-city');
    $input = $('input', $cwrapper);
    city = $(this).text();
    $input.val(city);
    $cwrapper.removeClass('open');
    set_cookie('from_city', from_city);
    set_cookie('to_city', null);
    callback = function() {
      var price_min;
      new_load_attr('result');
      new_load_attr('main');
      price_min = $('li.result b').text() + "元";
      return $('li.price').text(price_min);
    };
    return new_load_attr('filter', null, callback);
  });
  return $('body').on('click', 'li.result a', function() {
    var to_city;
    $('li.result a').removeClass('sel');
    $(this).addClass('sel');
    to_city = $(this).text();
    set_cookie('to_city', to_city);
    return new_load_attr('main');
  }).on('click', '.page_container ul.page li', function() {
    var default_page, max_page, page;
    default_page = parseInt($('#list_page').val());
    max_page = parseInt($('#page_total').val());
    if ($(this).attr('class') === 'prev') {
      if (default_page > 1) {
        page = default_page - 1;
      } else {
        page = default_page;
      }
    } else if ($(this).attr('class') === 'next') {
      if (default_page < max_page) {
        page = default_page + 1;
      } else {
        page = default_page;
      }
    } else if ($(this).attr('class') === 'begin') {
      page = 1;
    } else if ($(this).attr('class') === 'end') {
      page = max_page;
    } else {
      page = $(this).find('a').text().replace(/(^\s*)|(\s*$)/g, "");
    }
    $('#list_page').val(page);
    return new_load_attr('main', page);
  });
});
