// Generated by CoffeeScript 1.3.3
var PlanEditorView;

_.mixin({
  sum: function(list) {
    return _.reduce(list, (function(memo, num) {
      return memo + num;
    }), 0);
  }
});

PlanEditorView = (function() {

  function PlanEditorView() {}

  PlanEditorView.prototype.curr_day = null;

  PlanEditorView.prototype.days = 0;

  PlanEditorView.prototype.wl_popup_top0 = 63;

  PlanEditorView.prototype.initialize = function() {
    var lastScrollLeft, lastScrollTop, me, onScrollStop, _ref;
    me = this;
    if (!window.editor) {
      if ((_ref = window.console) == null) {
        window.console = {
          log: function() {},
          error: function() {}
        };
      }
    }
    $("li.done").mouseenter(function() {
      return $(this).find(".moveTip").show();
    }).mouseleave(function() {
      return $(this).find(".moveTip").hide();
    });
    $('.days').on('click', 'dl.day dt span.open', function() {
      var i;
      i = $(this).parents('.day').index('.days dl.day');
      return me.change_day(i);
    });
    if (!window.editor) {
      $('.nextDay').click(function() {
        return me.change_day(me.curr_day + 1);
      });
      $('.prevDay').click(function() {
        return me.change_day(me.curr_day - 1);
      });
    }
    onScrollStop = _.debounce((function() {
      return me.change_day(me.curr_day, false);
    }), 600);
    lastScrollLeft = 0;
    lastScrollTop = 0;
    window.onscroll = function(ev) {
      var sLeft, sTop;
      sLeft = $(window).scrollLeft();
      sTop = $(window).scrollTop();
      if (sLeft !== lastScrollLeft) {
        lastScrollLeft = sLeft;
        if (me.has_current_day()) {
          me.toggle_current_day(false);
          me.update_day_top();
        }
        me.update_current_day();
        onScrollStop();
      }
      if (sTop !== lastScrollTop) {
        lastScrollTop = sTop;
        return me.update_day_top();
      }
    };
    window.onresize = _.debounce(function() {
      me.update_map_height();
      me.set_days_position();
      return me.re_move_day();
    }, 300, false);
    this.change_curr_day = _.debounce(_.bind(this._change_curr_day, this), 300);
    return this.reinit();
  };

  PlanEditorView.prototype.change_day = function(i, immediate) {
    var me;
    if (immediate == null) {
      immediate = true;
    }
    me = this;
    this.toggle_current_day(true);
    return this.scroll_to_day(i, immediate, function() {
      return me.change_curr_day(me.curr_day);
    });
  };

  PlanEditorView.prototype.scroll_to_day = function(i, immediate, callback) {
    var do_show_day, duration, me, old_onscroll, scrolling, sleft;
    if (callback == null) {
      callback = function() {};
    }
    me = this;
    do_show_day = function() {
      var dtop;
      me.update_current_day();
      dtop = me.get_day_top();
      if (immediate) {
        $('.days dl.day.current').css({
          top: dtop.curr + 'px'
        });
        me.show_day_nav();
        return callback();
      } else {
        return $('.days dl.day.current').animate({
          top: dtop.curr + 'px'
        }, 200, 'easeOutCubic', function() {
          me.show_day_nav();
          return callback();
        });
      }
    };
    sleft = this.get_offset_by_day(i);
    if ($(window).scrollLeft() !== sleft) {
      old_onscroll = window.onscroll;
      scrolling = true;
      window.onscroll = function() {
        if (scrolling && $(document).scrollLeft() !== sleft) {
          return;
        }
        window.onscroll = old_onscroll;
        if ($(document).scrollLeft() === sleft) {
          return do_show_day();
        } else {
          return console.log("" + ($(document).scrollLeft()) + " isnt " + sleft);
        }
      };
      duration = immediate ? 0 : 100;
      return $('body').animate({
        scrollLeft: sleft
      }, duration, function() {
        return scrolling = false;
      });
    } else {
      return do_show_day();
    }
  };

  PlanEditorView.prototype.reinit = function() {
    var curr_day;
    this.curr_day = null;
    this.update_map_height();
    this.set_days_position();
    curr_day = this.get_day_by_offset($(document).scrollLeft());
    this.change_day(curr_day);
    this.update_day_top();
    return this.re_move_day();
  };

  PlanEditorView.prototype._change_curr_day = function() {
    console.log("change day to " + this.curr_day);
    if (window.editor && this.curr_day !== editor.schedule_view.currentOffset) {
      return editor.change_day_city(this.curr_day);
    }
  };

  PlanEditorView.prototype.get_day_by_offset = function(offset) {
    var curr_day, curr_left, day_width, tolerance;
    tolerance = 5;
    day_width = 150 + 10;
    curr_left = 30;
    return curr_day = parseInt(Math.max(0, offset - tolerance - 1 + curr_left) / day_width);
  };

  PlanEditorView.prototype.get_offset_by_day = function(day) {
    return day * 160;
  };

  PlanEditorView.prototype.update_current_day = function() {
    var curr_day, curr_day_left, dtop, navp, old_curr_day;
    curr_day = this.get_day_by_offset($(document).scrollLeft());
    old_curr_day = this.curr_day;
    this.curr_day = curr_day;
    if (old_curr_day === this.curr_day) {
      return;
    }
    dtop = this.get_day_top();
    $('.days dl.day.current').removeClass('current');
    $('.days dl.day').eq(curr_day).addClass('current');
    $('.days dl.day').css('top', dtop.other + 'px');
    curr_day_left = $('.days dl.day.current').css('left');
    curr_day_left = parseInt(curr_day_left);
    navp = {
      prev: curr_day_left - 20,
      next: curr_day_left + 150
    };
    $('.plan .prevDay').css('left', navp.prev + 'px');
    $('.plan .nextDay').css('left', navp.next + 'px');
    return this.show_day_nav();
  };

  PlanEditorView.prototype.show_day_nav = function() {
    $(".plan .prevDay").hide();
    $(".plan .nextDay").hide();
    if (this.has_current_day() && $(document).scrollTop() < 10) {
      if (this.curr_day !== 0) {
        $(".plan .prevDay").show();
      }
      if (this.curr_day !== this.days() - 1) {
        return $(".plan .nextDay").show();
      }
    }
  };

  PlanEditorView.prototype.days = function() {
    return $('.days dl.day').length;
  };

  PlanEditorView.prototype.has_current_day = function() {
    return !$('div.plan').hasClass('no-current-day');
  };

  PlanEditorView.prototype.toggle_current_day = function(onoff) {
    $('div.plan').toggleClass('no-current-day', !onoff);
    return $('div.plan').toggleClass('has-current-day', onoff);
  };

  PlanEditorView.prototype.update_day_top = function() {
    var dtop;
    dtop = this.get_day_top();
    $('.days dl.day.current').css('top', dtop.curr + 'px');
    $('.headerw').css('top', dtop.header + 'px');
    $('.days').toggleClass('hide-mini', $(document).scrollTop() > 5);
    $('.plan .cityChoose').css('top', dtop.city + 'px');
    $('.plan_title').css('top', dtop.title + 'px');
    $('.bigMap').css('top', dtop.map + 'px');
    return this.show_day_nav();
  };

  PlanEditorView.prototype.update_map_height = function() {
    var header_h, mapd, title_h;
    header_h = $('.headerw').outerHeight(true);
    title_h = $('.plan_title').outerHeight(true);
    mapd = {
      height: $(window).height() - header_h - title_h,
      top: header_h + title_h + $(document).scrollTop()
    };
    return $('.bigMap').height(mapd.height + 'px').css('top', mapd.top + 'px');
  };

  PlanEditorView.prototype.get_day_top = function() {
    var city_top, curr_day_top, curr_day_top0, dstop, header_h, header_top, headerw_h, map_top, other_day_top, title_h, title_top, wishlist_h;
    dstop = $(document).scrollTop();
    curr_day_top0 = 77;
    other_day_top = $(window).height() - $('.days dl.day dt').outerHeight(true) - $('.days dl.day').offsetParent().offset().top;
    curr_day_top = !this.has_current_day() ? other_day_top : Math.min(other_day_top, dstop + curr_day_top0);
    header_h = $('.header').outerHeight(true);
    wishlist_h = $('.wl_popup .tab_bar').outerHeight(true);
    headerw_h = $('.headerw').outerHeight(true);
    title_h = $('.plan_title').outerHeight(true);
    header_top = Math.min(header_h + wishlist_h, dstop);
    city_top = Math.max(155 - dstop, 40);
    title_top = Math.max(98 - dstop, 0);
    map_top = 135 - dstop;
    return {
      curr: curr_day_top,
      other: other_day_top,
      header: -header_top,
      city: city_top,
      title: title_top,
      map: map_top
    };
  };

  PlanEditorView.prototype.re_move_day = function() {
    var dtop;
    dtop = this.get_day_top();
    return $('.plan dl.day').not('.current').css('top', dtop.other + "px");
  };

  PlanEditorView.prototype.set_days_position = function() {
    var dayLeft, maxH, max_dayh, pland;
    maxH = 0;
    dayLeft = 0;
    $('.plan dl.day').each(function(i, e) {
      dayLeft = (150 + 10) * i + 30;
      return $(this).css("left", dayLeft + "px");
    });
    max_dayh = _.max($('.days dl.day').map(function() {
      return $(this).outerHeight(true);
    }));
    pland = {
      width: dayLeft + $(window).width() - 180,
      height: max_dayh + $(window).height() - $(".days dl.day dt").outerHeight(true)
    };
    $(".plan").width(pland.width).height(0);
    return $('.main-content').height(pland.height);
  };

  return PlanEditorView;

})();
